-- Teenybase Subscription Catalog Seed Data
-- Run this after applying the teenybase.ts migrations

-- Clear existing data
DELETE FROM subscription_catalog;

-- INSERT ENTRIES HERE (id is auto-generated UUID v4)

-- ENTERTAINMENT (16 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.netflix.Netflix', 'Netflix', 'entertainment', 'Stream thousands of TV shows, movies, and originals.', 'tv', 'https://netflix.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":15.49,"annualPriceUSD":139.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":22.99,"annualPriceUSD":229.99,"isBestValue":true},{"tier":"student","region":"US","monthlyPriceUSD":7.99,"annualPriceUSD":null,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.disney.disneyplus', 'Disney+', 'entertainment', 'Stream Disney, Pixar, Marvel, Star Wars, and more.', 'tv', 'https://disneyplus.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":13.99,"annualPriceUSD":139.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":19.99,"annualPriceUSD":199.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.hbo.hbomax', 'Max', 'entertainment', 'Stream HBO Originals, Warner Bros. movies, and DC content.', 'tv', 'https://max.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":15.99,"annualPriceUSD":149.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":20.99,"annualPriceUSD":199.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.hulu.plus', 'Hulu', 'entertainment', 'Stream TV shows, originals, and 100+ channels.', 'tv', 'https://hulu.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":17.99,"annualPriceUSD":179.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":22.99,"annualPriceUSD":229.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.amazon.aiv.AIVApp', 'Prime Video', 'entertainment', 'Stream Amazon Originals, movies, and TV shows.', 'tv', 'https://primevideo.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":139.00,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'tv.twitch', 'Twitch', 'entertainment', 'Live streaming for gamers and creators.', 'tv', 'https://twitch.tv', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":4.99,"annualPriceUSD":49.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.youtube.youtube', 'YouTube Premium', 'entertainment', 'Ad-free YouTube, Originals, and YouTube Music.', 'play.tv', 'https://youtube.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":13.99,"annualPriceUSD":139.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":22.99,"annualPriceUSD":229.99,"isBestValue":true},{"tier":"student","region":"US","monthlyPriceUSD":7.99,"annualPriceUSD":79.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.apple.AppleTVApp', 'Apple TV+', 'entertainment', 'Stream Apple Originals and exclusive shows.', 'tv', 'https://tv.apple.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":99.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.peacocktv.peacock', 'Peacock', 'entertainment', 'Stream NBCUniversal content, sports, and news.', 'tv', 'https://peacocktv.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":5.99,"annualPriceUSD":55.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":13.99,"annualPriceUSD":139.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.crunchyroll.crunchyroll', 'Crunchyroll', 'entertainment', 'Stream anime and manga content.', 'tv', 'https://crunchyroll.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":7.99,"annualPriceUSD":79.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":149.99,"isBestValue":true},{"tier":"student","region":"US","monthlyPriceUSD":4.99,"annualPriceUSD":49.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.pluto.tv', 'Pluto TV', 'entertainment', 'Free streaming with 100s of live TV channels.', 'tv', 'https://pluto.tv', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":0,"annualPriceUSD":0,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.tubi.Tubi', 'Tubi', 'entertainment', 'Free movies and TV shows with ads.', 'tv', 'https://tubi.tv', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":0,"annualPriceUSD":0,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.paramount.ParamountPlus', 'Paramount+', 'entertainment', 'Stream CBS, MTV, Paramount movies and originals.', 'tv', 'https://paramountplus.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":11.99,"annualPriceUSD":119.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":15.99,"annualPriceUSD":159.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.discovery.discoveryplus', 'Discovery+', 'entertainment', 'HGTV, Food Network, TLC and more on-demand.', 'tv', 'https://discoveryplus.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":8.99,"annualPriceUSD":89.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":13.99,"annualPriceUSD":139.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.sling.sling', 'Sling TV', 'entertainment', 'Live TV streaming with flexible packages.', 'tv', 'https://sling.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":40.00,"annualPriceUSD":400.00,"isBestValue":false},{"tier":"individual","region":"US","monthlyPriceUSD":55.00,"annualPriceUSD":550.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.philo.philo', 'Philo', 'entertainment', 'Affordable live TV and on-demand streaming.', 'tv', 'https://philo.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":25.00,"annualPriceUSD":250.00,"isBestValue":true}]'::jsonb, NOW());

-- MUSIC (10 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.spotify.client', 'Spotify', 'music', 'Stream millions of songs and podcasts ad-free.', 'music.note', 'https://spotify.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":10.99,"annualPriceUSD":109.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":16.99,"annualPriceUSD":169.99,"isBestValue":true},{"tier":"student","region":"US","monthlyPriceUSD":5.99,"annualPriceUSD":59.99,"isBestValue":false},{"tier":"duo","region":"US","monthlyPriceUSD":13.99,"annualPriceUSD":139.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.apple.Music', 'Apple Music', 'music', 'Stream 100M+ songs, album art, and live radio.', 'music.note', 'https://music.apple.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":10.99,"annualPriceUSD":109.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":16.99,"annualPriceUSD":169.99,"isBestValue":true},{"tier":"student","region":"US","monthlyPriceUSD":5.99,"annualPriceUSD":59.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.amazon.echo', 'Amazon Music Unlimited', 'music', 'Stream 100M+ songs with Alexa integration.', 'music.note', 'https://amazon.com/music', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":99.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":15.99,"annualPriceUSD":159.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.pandora', 'Pandora', 'music', 'Personalized radio and on-demand music streaming.', 'music.note', 'https://pandora.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":89.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":149.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.soundcloud.TuneCore', 'SoundCloud Go+', 'music', 'Stream and discover new music ad-free.', 'music.note', 'https://soundcloud.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":99.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.aspiro.TIDAL', 'Tidal', 'music', 'Hi-Fi music streaming with Dolby Atmos.', 'music.note', 'https://tidal.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":10.99,"annualPriceUSD":99.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":15.99,"annualPriceUSD":159.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.qobuz.Qobuz', 'Qobuz', 'music', 'Hi-Res music streaming up to 24-bit/192kHz.', 'music.note', 'https://qobuz.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.99,"annualPriceUSD":129.99,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":11.99,"annualPriceUSD":119.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.deezer.Deezer', 'Deezer', 'music', 'Music streaming with Flow and live radio.', 'music.note', 'https://deezer.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":10.99,"annualPriceUSD":99.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":16.99,"annualPriceUSD":169.99,"isBestValue":true},{"tier":"student","region":"US","monthlyPriceUSD":5.99,"annualPriceUSD":59.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.amazon.echoplus', 'Amazon Music Prime', 'music', 'Included with Prime, 100M+ songs.', 'music.note', 'https://amazon.com/music', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":0,"annualPriceUSD":0,"isBestValue":false}]'::jsonb, NOW());

-- PRODUCTIVITY (15 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.microsoft.Office', 'Microsoft 365', 'productivity', 'Word, Excel, PowerPoint, and more.', 'briefcase', 'https://microsoft.com/m365', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":99.99,"isBestValue":true},{"tier":"family","region":"US","monthlyPriceUSD":12.99,"annualPriceUSD":129.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.apple.pages', 'Apple iWork', 'productivity', 'Pages, Numbers, and Keynote for Apple devices.', 'briefcase', 'https://icloud.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":79.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.notion.id', 'Notion', 'productivity', 'All-in-one workspace for notes, docs, and wikis.', 'briefcase', 'https://notion.so', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":8.00,"annualPriceUSD":80.00,"isBestValue":true},{"tier":"team","region":"US","monthlyPriceUSD":15.00,"annualPriceUSD":144.00,"isBestValue":false},{"tier":"student","region":"US","monthlyPriceUSD":0,"annualPriceUSD":0,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.figma.Desktop', 'Figma', 'productivity', 'Collaborative design and prototyping tool.', 'briefcase', 'https://figma.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.00,"annualPriceUSD":144.00,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":45.00,"annualPriceUSD":540.00,"isBestValue":true},{"tier":"enterprise","region":"US","monthlyPriceUSD":75.00,"annualPriceUSD":900.00,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'us.zoom.xos', 'Zoom', 'productivity', 'Video conferencing and webinars.', 'briefcase', 'https://zoom.us', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":149.90,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":19.99,"annualPriceUSD":199.90,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.slack.Slack', 'Slack', 'productivity', 'Business communication and collaboration platform.', 'briefcase', 'https://slack.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":7.25,"annualPriceUSD":72.50,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":12.50,"annualPriceUSD":125.00,"isBestValue":true},{"tier":"enterprise","region":"US","monthlyPriceUSD":15.00,"annualPriceUSD":150.00,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.evernote.Evernote', 'Evernote', 'productivity', 'Notes, tasks, and organization tool.', 'briefcase', 'https://evernote.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":7.99,"annualPriceUSD":79.99,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":149.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.todoist', 'Todoist', 'productivity', 'Task and project management.', 'briefcase', 'https://todoist.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":4.00,"annualPriceUSD":36.00,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":6.00,"annualPriceUSD":60.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.adobe.Photoshop', 'Adobe Creative Cloud', 'productivity', 'Photoshop, Illustrator, and all Adobe apps.', 'briefcase', 'https://adobe.com/creativecloud', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":22.99,"annualPriceUSD":239.88,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":54.99,"annualPriceUSD":599.88,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.asana.ios', 'Asana', 'productivity', 'Team work and project management.', 'briefcase', 'https://asana.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":10.00,"annualPriceUSD":100.00,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":13.50,"annualPriceUSD":162.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.monday.monday', 'Monday.com', 'productivity', 'Work management platform for teams.', 'briefcase', 'https://monday.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.00,"annualPriceUSD":90.00,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":12.00,"annualPriceUSD":144.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.37signals.Basecamp', 'Basecamp', 'productivity', 'All-in-one project management and team communication.', 'briefcase', 'https://basecamp.com', 0, true, '[{"tier":"team","region":"US","monthlyPriceUSD":15.00,"annualPriceUSD":150.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.morgan.horde', 'ClickUp', 'productivity', 'One platform for all your work.', 'briefcase', 'https://clickup.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":7.00,"annualPriceUSD":70.00,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":5.00,"annualPriceUSD":50.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.linear.Linear', 'Linear', 'productivity', 'Streamlined issue tracking for software teams.', 'briefcase', 'https://linear.app', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":8.00,"annualPriceUSD":80.00,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":14.00,"annualPriceUSD":140.00,"isBestValue":true}]'::jsonb, NOW());

-- CLOUD STORAGE (5 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.apple.CloudServices', 'iCloud+', 'cloudStorage', 'Apple''s cloud storage with Photos, Drive, and more.', 'cloud', 'https://icloud.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":2.99,"annualPriceUSD":29.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":6.99,"annualPriceUSD":69.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.google.drive', 'Google One', 'cloudStorage', 'Storage for Google Drive, Gmail, and Photos.', 'cloud', 'https://one.google.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":2.99,"annualPriceUSD":29.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":6.99,"annualPriceUSD":69.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.getdropbox.Dropbox', 'Dropbox', 'cloudStorage', 'Cloud storage and file synchronization.', 'cloud', 'https://dropbox.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":11.99,"annualPriceUSD":119.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":22.99,"annualPriceUSD":229.99,"isBestValue":true},{"tier":"team","region":"US","monthlyPriceUSD":18.00,"annualPriceUSD":180.00,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.box.Box', 'Box', 'cloudStorage', 'Enterprise content management and collaboration.', 'cloud', 'https://box.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":10.00,"annualPriceUSD":100.00,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":25.00,"annualPriceUSD":250.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.microsoft.OneDrive', 'OneDrive', 'cloudStorage', 'Microsoft''s cloud storage with Office integration.', 'cloud', 'https://onedrive.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":1.99,"annualPriceUSD":19.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":6.99,"annualPriceUSD":69.99,"isBestValue":true}]'::jsonb, NOW());

-- HEALTH & FITNESS (5 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.peloton.app', 'Peloton', 'healthFitness', 'Fitness classes, workouts, and training.', 'heart.circle', 'https://onepeloton.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.99,"annualPriceUSD":129.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":19.99,"annualPriceUSD":199.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.strava.strava', 'Strava', 'healthFitness', 'Track runs, rides, and fitness activities.', 'heart.circle', 'https://strava.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":5.99,"annualPriceUSD":59.99,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":4.99,"annualPriceUSD":49.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.headspace.headspace', 'Headspace', 'healthFitness', 'Guided meditation and mindfulness.', 'heart.circle', 'https://headspace.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.99,"annualPriceUSD":69.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":19.99,"annualPriceUSD":99.99,"isBestValue":true},{"tier":"student","region":"US","monthlyPriceUSD":6.99,"annualPriceUSD":49.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.calm', 'Calm', 'healthFitness', 'Sleep, meditation, and relaxation content.', 'heart.circle', 'https://calm.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":69.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":24.99,"annualPriceUSD":119.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.myfitnesspal.mfp', 'MyFitnessPal', 'healthFitness', 'Food tracking and nutrition logging.', 'heart.circle', 'https://myfitnesspal.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":19.99,"annualPriceUSD":79.99,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":9.99,"annualPriceUSD":49.99,"isBestValue":false}]'::jsonb, NOW());

-- EDUCATION (9 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.duolingo.Duolingo', 'Duolingo', 'education', 'Language learning with gamified lessons.', 'book', 'https://duolingo.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.99,"annualPriceUSD":79.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":23.99,"annualPriceUSD":119.99,"isBestValue":true},{"tier":"student","region":"US","monthlyPriceUSD":6.99,"annualPriceUSD":39.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.masterclass.MasterClass', 'MasterClass', 'education', 'Learn from world-renowned experts.', 'book', 'https://masterclass.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":15.00,"annualPriceUSD":120.00,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":10.00,"annualPriceUSD":90.00,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.coursera.Coursera', 'Coursera', 'education', 'Online courses and professional certificates.', 'book', 'https://coursera.org', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":49.00,"annualPriceUSD":399.00,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":14.00,"annualPriceUSD":168.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.linkedin.LinkedInLearning', 'LinkedIn Learning', 'education', 'Business, tech, and creative skills courses.', 'book', 'https://linkedin.com/learning', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":29.99,"annualPriceUSD":299.99,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":24.99,"annualPriceUSD":249.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.skillshare.Skillshare', 'Skillshare', 'education', 'Creative and entrepreneurial skills.', 'book', 'https://skillshare.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":13.99,"annualPriceUSD":99.99,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":9.99,"annualPriceUSD":79.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.udemy.ios', 'Udemy Business', 'education', 'Unlimited access to 22K+ courses.', 'book', 'https://business.udemy.com', 0, true, '[{"tier":"team","region":"US","monthlyPriceUSD":12.50,"annualPriceUSD":150.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.pluralsight.ios', 'Pluralsight', 'education', 'Technology and creative skills training.', 'book', 'https://pluralsight.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":29.00,"annualPriceUSD":299.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.treehouse.Treehouse', 'Treehouse', 'education', 'Learn coding, design, and business skills.', 'book', 'https://teamtreehouse.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":25.00,"annualPriceUSD":250.00,"isBestValue":true}]'::jsonb, NOW());

-- NEWS (8 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.nytimes NYT', 'New York Times', 'news', 'News, investigations, and opinion.', 'newspaper', 'https://nytimes.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":17.00,"annualPriceUSD":204.00,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":25.00,"annualPriceUSD":300.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'wsj.WSJ', 'Wall Street Journal', 'news', 'Business news and financial analysis.', 'newspaper', 'https://wsj.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":179.00,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":12.99,"annualPriceUSD":159.00,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.washingtonpost.WP', 'Washington Post', 'news', 'National and international news coverage.', 'newspaper', 'https://washingtonpost.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":10.00,"annualPriceUSD":100.00,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":15.00,"annualPriceUSD":150.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.medium.medium', 'Medium', 'news', 'Writing and ideas from independent voices.', 'newspaper', 'https://medium.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":5.00,"annualPriceUSD":50.00,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":4.00,"annualPriceUSD":40.00,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.ft.FT', 'Financial Times', 'news', 'Global business and financial news.', 'newspaper', 'https://ft.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":15.00,"annualPriceUSD":180.00,"isBestValue":true},{"tier":"individual","region":"UK","monthlyPriceUSD":10.00,"annualPriceUSD":120.00,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.economist.Economist', 'The Economist', 'news', 'International news and business analysis.', 'newspaper', 'https://economist.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.00,"annualPriceUSD":144.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.thenation.thenation', 'The Atlantic', 'news', 'Journalism on politics, culture, and ideas.', 'newspaper', 'https://theatlantic.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.99,"annualPriceUSD":129.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.wired.wired', 'Wired', 'news', 'Technology and its impact on culture.', 'newspaper', 'https://wired.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":10.00,"annualPriceUSD":100.00,"isBestValue":true}]'::jsonb, NOW());

-- UTILITIES (9 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.nordvpn.NordVPN', 'NordVPN', 'utilities', 'Secure VPN for privacy and security.', 'wrench', 'https://nordvpn.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.99,"annualPriceUSD":59.99,"isBestValue":true},{"tier":"individual","region":"UK","monthlyPriceUSD":9.99,"annualPriceUSD":49.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.expressvpn.ExpressVPN', 'ExpressVPN', 'utilities', 'Lightning-fast VPN for secure browsing.', 'wrench', 'https://expressvpn.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.95,"annualPriceUSD":95.75,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.1password.1password', '1Password', 'utilities', 'Password manager for individuals and teams.', 'wrench', 'https://1password.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":2.99,"annualPriceUSD":35.88,"isBestValue":true},{"tier":"family","region":"US","monthlyPriceUSD":4.99,"annualPriceUSD":59.88,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":7.99,"annualPriceUSD":95.88,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.lastpass.LastPass', 'LastPass', 'utilities', 'Password manager and secure vault.', 'wrench', 'https://lastpass.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":3.00,"annualPriceUSD":36.00,"isBestValue":true},{"tier":"family","region":"US","monthlyPriceUSD":4.00,"annualPriceUSD":48.00,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.bitwarden.desktop', 'Bitwarden', 'utilities', 'Open source password manager.', 'wrench', 'https://bitwarden.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":0,"annualPriceUSD":0,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":3.33,"annualPriceUSD":40.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.surfshark.Surfshark', 'Surfshark VPN', 'utilities', 'Unlimited devices with secure VPN.', 'wrench', 'https://surfshark.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.95,"annualPriceUSD":47.77,"isBestValue":true},{"tier":"individual","region":"UK","monthlyPriceUSD":9.99,"annualPriceUSD":38.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.cyberghostvpn.ios', 'CyberGhost VPN', 'utilities', 'Privacy-focused VPN with global servers.', 'wrench', 'https://cyberghostvpn.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.99,"annualPriceUSD":56.94,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'ch.protonvpn', 'ProtonVPN', 'utilities', 'Secure Swiss VPN with no logs.', 'wrench', 'https://protonvpn.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":4.99,"annualPriceUSD":47.88,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":95.88,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.mullvad.MullvadVPN', 'Mullvad VPN', 'utilities', 'Anonymous VPN focused on privacy.', 'wrench', 'https://mullvad.net', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":5.50,"annualPriceUSD":55.00,"isBestValue":true}]'::jsonb, NOW());

-- SOCIAL (4 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.tinder.Tinder', 'Tinder+', 'social', 'Dating app with unlimited likes and more.', 'person.2', 'https://tinder.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":29.99,"annualPriceUSD":299.99,"isBestValue":true},{"tier":"individual","region":"UK","monthlyPriceUSD":24.99,"annualPriceUSD":249.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.bumble.Bumble', 'Bumble Boost', 'social', 'Dating app where women make the first move.', 'person.2', 'https://bumble.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":24.99,"annualPriceUSD":179.99,"isBestValue":true},{"tier":"individual","region":"UK","monthlyPriceUSD":19.99,"annualPriceUSD":149.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.hinge.Hinge', 'Hinge Preferred', 'social', 'Dating app designed to be deleted.', 'person.2', 'https://hinge.co', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":24.99,"annualPriceUSD":209.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.discord.Discord', 'Discord Nitro', 'social', 'Enhanced Discord with perks and upgrades.', 'person.2', 'https://discord.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":99.99,"isBestValue":true},{"tier":"individual","region":"UK","monthlyPriceUSD":8.99,"annualPriceUSD":89.99,"isBestValue":false}]'::jsonb, NOW());

-- SHOPPING (4 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.amazon.aiv.AIVApp', 'Amazon Prime', 'shopping', 'Free shipping, streaming, and more.', 'cart', 'https://amazon.com/prime', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":139.00,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":8.99,"annualPriceUSD":89.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.costcoplus.costco', 'Costco Membership', 'shopping', 'Warehouse club with bulk savings.', 'cart', 'https://costco.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":6.00,"annualPriceUSD":60.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.walmart.Walmart', 'Walmart+', 'shopping', 'Free delivery, fuel discounts, and more.', 'cart', 'https://walmart.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.95,"annualPriceUSD":98.00,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.target.Target', 'Target Circle', 'shopping', 'Savings and exclusive deals at Target.', 'cart', 'https://target.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":0,"annualPriceUSD":0,"isBestValue":false}]'::jsonb, NOW());

-- FOOD (4 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.doordash.DoorDash', 'DashPass', 'food', 'Free delivery and reduced fees on orders.', 'fork.knife', 'https://doordash.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":95.00,"isBestValue":true},{"tier":"individual","region":"UK","monthlyPriceUSD":7.99,"annualPriceUSD":79.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.ubereats.UberEats', 'Uber Eats Pass', 'food', 'Unlimited free delivery on orders.', 'fork.knife', 'https://ubereats.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":99.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.grubhub.grubhub', 'Grubhub+', 'food', 'Free delivery and exclusive offers.', 'fork.knife', 'https://grubhub.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":99.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.hellofresh.HelloFresh', 'HelloFresh', 'food', 'Meal kit delivery service.', 'fork.knife', 'https://hellofresh.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":59.99,"isBestValue":true},{"tier":"family","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":89.99,"isBestValue":false}]'::jsonb, NOW());

-- SPORTS (10 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.espn.espn-plus', 'ESPN+', 'sports', 'Live sports, original shows, and exclusives.', 'sportscourt', 'https://espn.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":10.99,"annualPriceUSD":109.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.nfl.nfl-plus', 'NFL+', 'sports', 'Stream live NFL games and on-demand content.', 'sportscourt', 'https://nfl.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":6.99,"annualPriceUSD":49.99,"isBestValue":true},{"tier":"individual","region":"US","monthlyPriceUSD":13.99,"annualPriceUSD":99.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.nba.league', 'NBA League Pass', 'sports', 'Watch every NBA game live or on-demand.', 'sportscourt', 'https://nba.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":99.99,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":24.99,"annualPriceUSD":149.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.mlbf一次性.MLB', 'MLB.TV', 'sports', 'Watch live out-of-market MLB games.', 'sportscourt', 'https://mlb.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":99.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.nhl.GC', 'NHL Live', 'sports', 'Stream live and archived hockey games.', 'sportscourt', 'https://nhl.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":12.99,"annualPriceUSD":99.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.microsoft.xboxgamepass', 'Xbox Game Pass Ultimate', 'sports', 'Console, PC gaming, and cloud gaming in one.', 'sportscourt', 'https://xbox.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":16.99,"annualPriceUSD":169.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.playstation.plus', 'PlayStation Plus', 'sports', 'Online multiplayer and free monthly games.', 'sportscourt', 'https://playstation.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":59.99,"isBestValue":false},{"tier":"individual","region":"US","monthlyPriceUSD":17.99,"annualPriceUSD":119.99,"isBestValue":true},{"tier":"individual","region":"US","monthlyPriceUSD":22.99,"annualPriceUSD":159.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.nintendo.SwitchOnline', 'Nintendo Switch Online', 'sports', 'Online multiplayer and classic game library.', 'sportscourt', 'https://nintendo.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":3.99,"annualPriceUSD":34.99,"isBestValue":false},{"tier":"family","region":"US","monthlyPriceUSD":7.99,"annualPriceUSD":49.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.ea.EAPlay', 'EA Play', 'sports', 'Play new games first and get rewards.', 'sportscourt', 'https://ea.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":4.99,"annualPriceUSD":39.99,"isBestValue":false},{"tier":"individual","region":"UK","monthlyPriceUSD":3.99,"annualPriceUSD":34.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.ubisoft.ubisoft', 'Ubisoft+', 'sports', 'Access to Ubisoft''s full game library.', 'sportscourt', 'https://ubisoft.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":17.99,"annualPriceUSD":119.99,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":29.99,"annualPriceUSD":299.99,"isBestValue":true}]'::jsonb, NOW());

-- FINANCE (5 entries)
INSERT INTO subscription_catalog (id, bundle_id, name, category, description, icon_name, website_url, trial_days, can_pause, supported_tiers, last_updated) VALUES
(uuid_generate_v4(), 'com.ynab.YNAB', 'YNAB', 'finance', 'Budgeting app for financial peace of mind.', 'dollarsign.circle', 'https://ynab.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":99.99,"isBestValue":true},{"tier":"individual","region":"UK","monthlyPriceUSD":11.99,"annualPriceUSD":79.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.rocketmoney.RocketMoney', 'Rocket Money', 'finance', 'Track and cancel subscriptions, negotiate bills.', 'dollarsign.circle', 'https://rocketmoney.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":6.00,"annualPriceUSD":48.00,"isBestValue":true},{"tier":"individual","region":"UK","monthlyPriceUSD":4.99,"annualPriceUSD":39.99,"isBestValue":false}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.clearchannel.iHeartRadio', 'iHeartRadio All Access', 'finance', 'Music, radio, and podcasts with premium.', 'dollarsign.circle', 'https://iheart.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":9.99,"annualPriceUSD":99.99,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.tradingview.TradingView', 'TradingView', 'finance', 'Charts, market data, and trading insights.', 'dollarsign.circle', 'https://tradingview.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":14.99,"annualPriceUSD":155.88,"isBestValue":false},{"tier":"team","region":"US","monthlyPriceUSD":29.95,"annualPriceUSD":299.40,"isBestValue":true}]'::jsonb, NOW()),
(uuid_generate_v4(), 'com.empiretoday.Robinhood', 'Robinhood Gold', 'finance', 'Premium investing with instant deposits and more.', 'dollarsign.circle', 'https://robinhood.com', 0, true, '[{"tier":"individual","region":"US","monthlyPriceUSD":5.00,"annualPriceUSD":60.00,"isBestValue":true}]'::jsonb, NOW());

-- Verify count
SELECT COUNT(*) as total_entries FROM subscription_catalog;
